import type { Metadata } from "next";
import { Poppins, Audiowide, Orbitron } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { brandName } from "@/constants/brandname.constants";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const audiowide = Audiowide({
  variable: "--font-audiowide",
  subsets: ["latin"],
  weight: ["400"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: `${brandName} | Home`,
  description: "Generated by create next app",
  icons: {
    icon: "/assets/cs-fav.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${audiowide.variable} ${orbitron.variable} font-poppins bg-background h-full w-full min-w-screen overflow-x-hidden antialiased`}
      >
        {/* <LenisProvider> */}
        {children}
        <Analytics />
        <SpeedInsights />
        {/* </LenisProvider> */}
      </body>
    </html>
  );
}
